# Generated by Django 4.1 on 2022-08-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='products',
            field=models.TextField(default=0, max_length=1000),
        ),
    ]
