# Generated by Django 4.1 on 2022-08-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(default='images/services-icon.png', upload_to='images/'),
        ),
    ]
