# Generated by Django 4.1 on 2022-08-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.IntegerField()),
                ('service', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
